// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoTienda.Data;

#nullable disable

namespace ProyectoTienda2.Migrations
{
    [DbContext(typeof(ProyectoTiendaContext))]
    [Migration("20230607152105_si")]
    partial class si
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoTienda.Models.Realme", b =>
                {
                    b.Property<int>("Idrealme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idrealme"));

                    b.Property<string>("Namerealme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("unitpricerealme")
                        .HasColumnType("float");

                    b.HasKey("Idrealme");

                    b.ToTable("realmes");

                    b.HasData(
                        new
                        {
                            Idrealme = 1,
                            Namerealme = "Realme gt",
                            unitpricerealme = 599.99000000000001
                        });
                });

            modelBuilder.Entity("ProyectoTienda.Models.Xiaomi", b =>
                {
                    b.Property<int>("Idxiaomi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idxiaomi"));

                    b.Property<string>("Namexiaomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("unitpricexiaomi")
                        .HasColumnType("float");

                    b.HasKey("Idxiaomi");

                    b.ToTable("xiaomis");

                    b.HasData(
                        new
                        {
                            Idxiaomi = 1,
                            Namexiaomi = "Marcela Padilla",
                            unitpricexiaomi = 9.9900000000000002
                        });
                });

            modelBuilder.Entity("ProyectoTienda.Models.iphone", b =>
                {
                    b.Property<int>("Idiphone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idiphone"));

                    b.Property<string>("Nameiphone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("unitpriceiphone")
                        .HasColumnType("float");

                    b.HasKey("Idiphone");

                    b.ToTable("iphones");

                    b.HasData(
                        new
                        {
                            Idiphone = 1,
                            Nameiphone = "iphone 12",
                            unitpriceiphone = 999.99000000000001
                        });
                });

            modelBuilder.Entity("ProyectoTienda.Models.products", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("unitprice")
                        .HasColumnType("float");

                    b.HasKey("productId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            productName = "note 20",
                            unitprice = 9.9900000000000002
                        },
                        new
                        {
                            productId = 2,
                            productName = "s21",
                            unitprice = 999.0
                        },
                        new
                        {
                            productId = 3,
                            productName = "s22",
                            unitprice = 5555.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
