// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoTienda.Data;

#nullable disable

namespace ProyectoTienda2.Migrations
{
    [DbContext(typeof(ProyectoTiendaContext))]
    partial class ProyectoTiendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoTienda.Models.products", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("unitprice")
                        .HasColumnType("float");

                    b.HasKey("productId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            productName = "Samsung Galaxy S23",
                            unitprice = 959.0
                        },
                        new
                        {
                            productId = 2,
                            productName = "Samsung Galaxy S23+",
                            unitprice = 1209.0
                        },
                        new
                        {
                            productId = 3,
                            productName = "Samsung Galaxy S23 Ultra",
                            unitprice = 1409.0
                        },
                        new
                        {
                            productId = 4,
                            productName = "Samsung Galaxy A54 5G ",
                            unitprice = 499.0
                        },
                        new
                        {
                            productId = 5,
                            productName = "Samsung Galaxy A34 5G",
                            unitprice = 469.0
                        },
                        new
                        {
                            productId = 6,
                            productName = "Samsung Galaxy A53 5G",
                            unitprice = 335.0
                        },
                        new
                        {
                            productId = 7,
                            productName = "Samsung Galaxy A13",
                            unitprice = 179.0
                        },
                        new
                        {
                            productId = 8,
                            productName = "Samsung Galaxy A14",
                            unitprice = 185.0
                        },
                        new
                        {
                            productId = 9,
                            productName = "Samsung Galaxy A04 Core",
                            unitprice = 170.0
                        },
                        new
                        {
                            productId = 10,
                            productName = "Samsung Galaxy A10s",
                            unitprice = 100.0
                        },
                        new
                        {
                            productId = 12,
                            productName = "Xiaomi 13",
                            unitprice = 650.0
                        },
                        new
                        {
                            productId = 13,
                            productName = "Xiaomi 13 pro",
                            unitprice = 750.0
                        },
                        new
                        {
                            productId = 14,
                            productName = "Xiaomi 12S Ultra",
                            unitprice = 1200.0
                        },
                        new
                        {
                            productId = 15,
                            productName = "Redmi note 12",
                            unitprice = 190.0
                        },
                        new
                        {
                            productId = 16,
                            productName = "Redmi note 12 Pro",
                            unitprice = 270.0
                        },
                        new
                        {
                            productId = 17,
                            productName = "Redmi note 12 Pro plus",
                            unitprice = 335.0
                        },
                        new
                        {
                            productId = 18,
                            productName = "Redmi 9c",
                            unitprice = 80.0
                        },
                        new
                        {
                            productId = 19,
                            productName = "Redmi 10C",
                            unitprice = 92.0
                        },
                        new
                        {
                            productId = 20,
                            productName = "Redmi 11C",
                            unitprice = 90.0
                        },
                        new
                        {
                            productId = 21,
                            productName = "Redmi 12C",
                            unitprice = 95.0
                        },
                        new
                        {
                            productId = 22,
                            productName = "iphone 12",
                            unitprice = 990.0
                        },
                        new
                        {
                            productId = 23,
                            productName = "iphone 12 Pro",
                            unitprice = 1100.0
                        },
                        new
                        {
                            productId = 24,
                            productName = "iphone 12 Pro Max",
                            unitprice = 1200.0
                        },
                        new
                        {
                            productId = 25,
                            productName = "iphone 13",
                            unitprice = 900.0
                        },
                        new
                        {
                            productId = 26,
                            productName = "iphone 13 Pro ",
                            unitprice = 1100.0
                        },
                        new
                        {
                            productId = 27,
                            productName = "iphone 13 Pro Max",
                            unitprice = 1200.0
                        },
                        new
                        {
                            productId = 28,
                            productName = "iphone 14",
                            unitprice = 900.0
                        },
                        new
                        {
                            productId = 29,
                            productName = "iphone 14 Pro",
                            unitprice = 1100.0
                        },
                        new
                        {
                            productId = 30,
                            productName = "iphone 14 Plus",
                            unitprice = 1150.0
                        },
                        new
                        {
                            productId = 31,
                            productName = "iphone 14 Pro Max",
                            unitprice = 1200.0
                        },
                        new
                        {
                            productId = 32,
                            productName = "Realme Gt 2 Pro",
                            unitprice = 690.0
                        },
                        new
                        {
                            productId = 33,
                            productName = "Realme GT 2",
                            unitprice = 500.0
                        },
                        new
                        {
                            productId = 34,
                            productName = "Samsung Galaxy A10s",
                            unitprice = 100.0
                        },
                        new
                        {
                            productId = 35,
                            productName = "Realme GT ",
                            unitprice = 450.0
                        },
                        new
                        {
                            productId = 36,
                            productName = "Realme 9 Pro plus",
                            unitprice = 350.0
                        },
                        new
                        {
                            productId = 37,
                            productName = "Realme GT Master Edition",
                            unitprice = 340.0
                        },
                        new
                        {
                            productId = 38,
                            productName = "Realme 9 Pro",
                            unitprice = 330.0
                        },
                        new
                        {
                            productId = 39,
                            productName = "Realme C35",
                            unitprice = 199.0
                        },
                        new
                        {
                            productId = 40,
                            productName = "Realme C25Y",
                            unitprice = 179.0
                        },
                        new
                        {
                            productId = 41,
                            productName = "Realme C31",
                            unitprice = 159.0
                        },
                        new
                        {
                            productId = 42,
                            productName = "Realme C21Y",
                            unitprice = 130.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
