// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tienda2.Data;

#nullable disable

namespace Tienda2.Migrations
{
    [DbContext(typeof(LogingContext))]
    partial class LogingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tienda2.Models.Loging", b =>
                {
                    b.Property<string>("usuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("usuario");

                    b.ToTable("logings");

                    b.HasData(
                        new
                        {
                            usuario = "Alejandro",
                            contraseña = "Bruno123"
                        },
                        new
                        {
                            usuario = "Steven",
                            contraseña = "Pompi"
                        },
                        new
                        {
                            usuario = "Francisco",
                            contraseña = "HijodeAlejandro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
